name: CI (e2e)

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"
  workflow_call:
  merge_group:

concurrency:
  group: ci-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload-for-e2e-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: save trustify-ui image
        run: |
          docker build . -t ghcr.io/trustification/trustify-ui:pr-test -f Dockerfile
          docker save -o /tmp/trustify-ui.tar ghcr.io/trustification/trustify-ui:pr-test

      - name: Upload trustify-ui image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trustify-ui
          path: /tmp/trustify-ui.tar
          retention-days: 1

  discover-envs-for-e2e-ci:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-outputs.outputs.image_tag }}
    steps:
      - name: Extract vars for Pull Request
        shell: bash
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        run: |
          branch=${{ github.event.pull_request.base.ref }}
          image_tag="latest"
          if [[ "$branch" != "main" ]]; then
            image_tag="${branch#release/}"
          fi
          echo "image_tag=$image_tag" >> $GITHUB_ENV
      - name: Extract vars for Push
        shell: bash
        if: ${{ github.event_name != 'pull_request' && github.event_name != 'merge_group' }}
        run: |
          branch=$(echo ${GITHUB_REF#refs/heads/})
          image_tag="latest"
          if [[ "$branch" != "main" ]]; then
            image_tag="${branch#release/}"
          fi
          echo "image_tag=$image_tag" >> $GITHUB_ENV
      - name: Set outputs
        id: set-outputs
        run: |
          echo ${{ env.image_tag }}
          echo "image_tag=${{ env.image_tag }}" >> "$GITHUB_OUTPUT"

  run-e2e-ci:
    needs:
      - build-and-upload-for-e2e-ci
      - discover-envs-for-e2e-ci
    uses: ./.github/workflows/ci-e2e-template.yaml
    with:
      artifact: trustify-ui
      ui_image: ghcr.io/trustification/trustify-ui:pr-test
      server_image: ghcr.io/trustification/trustd:${{ needs.discover-envs-for-e2e-ci.outputs.image_tag }}
